const shifts=[{time:'12.15–15.00',tasks:{'Toegang':['Machine Head','Estrella','Sonata'],'Munt/merch':['Killswitch','Evanescence','Metallica','Miller','Rammstein'],'Bar':['Riffmaster','Jorn','Otep','Type O','Djevel','Lindemans'],'Conciërge':['Sinner'],'Backstagebar':['Corona','Manowar'],'Backstage':['Djentleman','Lamb of God','Tool','Mastodon'],'Reserve':['Jopen']}},{time:'15.00–18.00',tasks:{'Toegang':['Rammstein','Lindemans'],'Munt/merch':['Killswitch','Evanescence','Type O','Metallica','Miller'],'Bar':['Riffmaster','Jorn','Machine Head','Jopen','Djevel','Tremonti','Manowar'],'Conciërge':['Estrella','Sonata'],'Backstagebar':['Corona','Otep'],'Backstage':['Djentleman','Doom','Lamb of God','Tool','Mastodon']}},{time:'18.00–21.00',tasks:{'Toegang':['Danzig','Franziskaner'],'Munt/merch':['Sonata','Jopen'],'Bar':['Riffmaster','Otep','Tremonti','Manowar','Anthrax','Jag Panzer'],'Conciërge':['Sinner','Estrella'],'Backstagebar':['Corona','Rammstein','Killswitch'],'Backstage':['Djentleman','Doom','Lamb of God','Tool','Mastodon']}},{time:'21.00–23.00',tasks:{'Toegang':['Running Wild'],'Munt/merch':['Danzig','Estrella'],'Bar':['Riffmaster','Jopen','Sonata','Tremonti','Manowar','Franziskaner','Anthrax'],'Conciërge':['Sinner','Jag Panzer'],'Backstagebar':['Corona','Otep'],'Backstage':['Djentleman','Doom','Lamb of God','Tool','Mastodon']}}];
const taskInfo={'Toegang':{lead:'Sonja',items:['Scan tickets met de Stager-app.','Controleer leeftijd en polsbandje; schakel bij twijfel security in.','Entree aan de deur: €40.','Blijf gastvrij en ga niet zelf in discussie.']},'Munt/merch':{lead:'Evelyne',items:['Munten, merch en garderobe; PIN heeft voorkeur.','Munt €3,30 en halve munt €1,65.','Houd wachtrijen en rolstoelroutes vrij.']},'Bar':{lead:'Djenna',items:['Drank uitsluitend tegen munten.','Strikt NIX18.','Niet schenken aan zichtbaar dronken bezoekers.','Stem af met de tweede bar.']},'Conciërge':{lead:'Simon',items:['Controleer terrein en toiletten.','Houd nooduitgangen en routes vrij.','Handhaaf het rookverbod.','Meld gladheid, verstoppingen en defecten.']},'Backstagebar':{lead:'Collin',items:['Alleen toegang met backstagebandje.','Blikwerk mag niet het terrein op.','Schenk verantwoord en houd doorgangen vrij.']},'Backstage':{lead:'Django',items:['Ontvang bands en stagemanagement.','Houd apparatuur uit vluchtwegen.','Ondersteun alleen op aanwijzing van security of veiligheidscoördinator.']},'Reserve':{lead:'Sonja',items:['Blijf bereikbaar.','Spring bij waar drukte of uitval ontstaat.']}};
const contacts=[['Veiligheidscoördinator','Ruud van Hees',null,'Zie vrijwilligersapp'],['Plaatsvervangend locatiemanager','Noortje van Ginneken',null,'Zie vrijwilligersapp'],['Locatiemanager','Jeroen van Tiggelen',null,'Zie vrijwilligersapp'],['Plaatsvervangend veiligheidscoördinator','Yomi Borgmans',null,'Zie WhatsAppgroep'],['Beveiliging VAW','Security',null,'Zie vrijwilligersapp'],['EHBO','EHBO-post',null,'Zie WhatsAppgroep'],['Horeca-coördinator','Djenna Stevens',null,'Zie vrijwilligersapp'],['Vrijwilligerscoördinator','Sonja van Oers',null,'Zie vrijwilligersapp'],['Politie / brandweer / ambulance','Spoed','112',null],['Politie','Geen spoed','0900-8844',null],['Huisartsenpost Roosendaal','Huisartsenpost','0165-530200',null]];
const day=[['11.00','Ontvangst shift 1 en korte briefing'],['11.30','Lunch; om 12.00 uur groepsfoto'],['12.15','Start shift 1'],['12.30','Festival open'],['13.00','Eerste band'],['15.00','Start shift 2'],['17.00–19.00','Eten; stem pauzes onderling af'],['18.00','Start shift 3'],['21.00','Start shift 4'],['23.00','Festival sluit, bar dicht, lichten aan'],['23.00–…','Opruimen en afbouw'],['00.30','Vrijwilligersafterparty met pizza backstage']];
const rules=['Draag tijdens je shift het ROA-shirt en blijf nuchter.','Roken is verboden in alle binnenruimtes van The Loods.','Strikt NIX18. Drugs zijn niet toegestaan.','Vraag naar Angela, intimidatie of ongewenst gedrag: schakel security in.','Speel geen held: schaal liever te vroeg op.','Houd nooduitgangen, vluchtwegen, rolstoelroutes en EHBO-routes vrij.','Spreek bezoekers gelijkwaardig aan en vraag eerst of hulp gewenst is.','Wisselen kan alleen via Sonja of de taakcoördinator.'];
const cleanup=[
{order:1,task:'Helpen Vincent',crew:'2 mensen',open:true,details:'Spullen in Vincents vak. SPULLEN IN VINCENTS VAK!'},
{order:1,task:'Banken en tafels terrein opruimen',crew:'4 mensen',open:true,details:'Materiaal: trolleys. Naar B&P-vak. Stapel de trolley volgens voorschrift; kom je er niet uit, vraag de coördinator.'},
{order:1,task:'Hekwerkzeilen en banners losknippen',crew:'4 mensen',open:true,details:'Materiaal: emmer voor tie-rips en kniptang. Voor het StAM-hok in 2 nette stapels: banners apart en hekwerkzeilen apart. Loop vóór de hekwerkcrew uit; tie-rips meenemen in emmers en niet op het terrein achterlaten.',sunday:'Zondagcrew: in StAM-hok leggen.'},
{order:1,task:'Hekwerken losmaken en opruimen',crew:'3 mensen',open:true,details:'Materiaal: boormachientje met juiste dop. Op de hekwerkbokken. Afstemmen met de banner-afknipcrew. Om en om wegzetten, blokken onderin, beugels in de bijbehorende bak.',sunday:'Zondagcrew: check op tie-rips in het veld.'},
{order:1,task:'Bordjes en aankleding (planken)',crew:'2 mensen',open:true,details:'Materiaal en opslag vrijdag ter plaatse bekijken. Ben er zuinig op 😉.'},
{order:1,task:'Bar buiten',crew:'3 mensen',open:true,details:'Materiaal: tangetje. Natte bar, dranken en koelingen → Van Dorst-vak. Lichtsnoer en houten bardelen → JaXX-vak. Elektra → Boels-vak. Eerst buitenbar, daarna binnenbar. Tie-rips direct in emmers en niet op terrein achterlaten.',sunday:'Zondagcrew: voorraad tellen.'},
{order:1,task:'Munten',crew:'3 mensen',open:true,details:'Materiaal: tangetje. Geld en munten → StAM-hok. Merch en pinapparatuur → StAM-hok. Elektra → Boels-vak. Lichtsnoer → JaXX-vak. Horecamunten eerst uittellen en geld/munten aan StAM overdragen vóór het opruimen.'},
{order:1,task:'Toegang',crew:'2 mensen',open:true,details:'Materiaal: tangetje. Geld, munten en bandjes → StAM-hok. Pinapparatuur → StAM-hok. Elektra → Boels-vak. Lichtsnoer → JaXX-vak.'},
{order:1,task:'Backstagebar',crew:'Geen aparte bezetting',open:false,details:'Leeg; iedereen ruimt mee op.'},
{order:1,task:'Binnenmarkt',crew:'Aantal nog bepalen',open:true,details:'Materiaal: trolley voor banken en tafels. Volle trolley → B&P-vak. Elektra → Boels-vak. Zwarte klapstoelen → B&P-vak. Plafondlampen niet opruimen; tafels en banken opstapelen volgens voorschrift. Standhouders zo nodig aansporen op te ruimen.',sunday:'Zondagcrew: plafondlampen.'},
{order:2,task:'Kabelgoten opruimen',crew:'2 sterke mensen',open:true,details:'Materiaal: speciaal rek. Naar Boels-vak. Rustig blijven; forceren werkt niet.'},
{order:2,task:'Toiletwagens',crew:'1 persoon',open:true,details:'Water en elektra loskoppelen, deuren dicht. Tuinslangen en bijzondere koppelingen → StAM-hok. Gele slangen en elektra → Boels-vak.',sunday:'Deel zondag: inspectie op schoon en heel, zo nodig poetsen en schade melden.'},
{order:2,task:'Bar binnen',crew:'Aantal nog bepalen',open:true,details:'Materiaal: tangetje. Natte bar, dranken en koelingen → Van Dorst-vak. Lichtsnoer en houten bardelen → JaXX-vak. Elektra → Boels-vak. Pas na de buitenbar opruimen. Tie-rips direct in vuilnis en niet op terrein achterlaten.'},
{order:2,task:'Catering, EHBO-tent en merchtent',crew:'Aantal nog bepalen',open:true,details:'Materiaal: trolley voor banken en tafels. Volle trolley → B&P-vak. Elektra → Boels-vak. Zwarte klapstoelen → B&P-vak. Tafels en banken opstapelen volgens voorschrift. Standhouders zo nodig aansporen op te ruimen.'},
{order:3,task:'Terrein vegen',crew:'4–6 mensen',open:true,details:'Materiaal: bezems, sneeuwschuiven of scheppen. Afval in de vuilnisbakken. Netjes, maar hoeft niet brandschoon.',sunday:'Zondagcrew: nalopen of er nog gekke dingen op het terrein liggen.'},
{order:3,task:'Binnen vegen bij StAM-stage',crew:'4–6 mensen',open:true,details:'Materiaal: bezems, sneeuwschuiven of scheppen. Afval in de vuilnisbakken. Netjes, maar hoeft niet brandschoon.',sunday:'Zondagcrew: nalopen of er nog gekke dingen in de zaal liggen.'},
{order:4,task:'Vuilnisbakken groeperen voor ophaal',crew:'2 mensen',open:true,details:'Geen materiaal nodig. Groeperen waar ze afgeleverd zijn.'},
{order:5,task:'Overgebleven verlichting, elektra, kabels en verdeelkasten',crew:'8 mensen',open:true,details:'Naar Boels-vak. Dit is het laatste werk; grote terreinlampen als allerlaatste.'},
{order:'Zondag',task:'Toiletten binnen',crew:'Aantal nog bepalen',open:true,details:'Voor zondag.',sunday:'Inspectie op schoon en heel, zo nodig poetsen en schade melden.'}
];
const volunteer=document.getElementById('volunteer');[...new Set(shifts.flatMap(s=>Object.values(s.tasks).flat()))].sort().forEach(p=>{const o=document.createElement('option');o.value=p;o.textContent=p;volunteer.appendChild(o)});volunteer.addEventListener('change',()=>{const name=volunteer.value,out=document.getElementById('personalSchedule');if(!name){out.innerHTML='<p class="muted">Kies je naam om je persoonlijke diensten te zien.</p>';return}const m=[];shifts.forEach(s=>Object.entries(s.tasks).forEach(([task,names])=>{if(names.includes(name))m.push({time:s.time,task})}));out.innerHTML=m.map(x=>`<div class="shift"><strong>${x.time}</strong><br><span class="badge">${x.task}</span><div class="muted">Aanspreekpunt: ${taskInfo[x.task]?.lead||'Sonja'}</div></div>`).join('')});
document.getElementById('dayTimeline').innerHTML=day.map(x=>`<div class="event"><div class="time">${x[0]}</div><div>${x[1]}</div></div>`).join('');
const tb=document.getElementById('taskButtons');Object.keys(taskInfo).forEach(t=>{const b=document.createElement('button');b.className='task-btn';b.textContent=t;b.type='button';b.addEventListener('click',()=>{document.querySelectorAll('.task-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=taskInfo[t];document.getElementById('taskDetail').innerHTML=`<h2>${t}</h2><p><strong>Aanspreekpunt:</strong> ${d.lead}</p><ul>${d.items.map(x=>`<li>${x}</li>`).join('')}</ul>`});tb.appendChild(b)});
function renderContacts(q=''){document.getElementById('contacts').innerHTML=contacts.filter(c=>c.filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase())).map(c=>{const action=c[2]?`<a class="call" href="tel:${c[2].replace(/[^0-9+]/g,'')}">${c[2]}</a>`:`<span class="call ref">${c[3]}</span>`;return `<div class="phone"><div><strong>${c[1]}</strong><div class="muted">${c[0]}</div></div>${action}</div>`}).join('')}renderContacts();document.getElementById('contactSearch').addEventListener('input',e=>renderContacts(e.target.value));document.getElementById('rules').innerHTML=rules.map(r=>`<div class="rule">${r}</div>`).join('');
const cleanupList=document.getElementById('cleanupList');let last=null;cleanup.forEach(x=>{if(x.order!==last){cleanupList.insertAdjacentHTML('beforeend',`<div class="phase">${x.order==='Zondag'?'Zondagcrew':'Volgorde '+x.order}</div>`);last=x.order}cleanupList.insertAdjacentHTML('beforeend',`<div class="cleanup"><div class="cleanup-head"><div class="cleanup-title">${x.task}</div><span class="crew ${x.open?'open':''}">${x.crew}</span></div><div class="details">${x.details}</div>${x.open?'<div class="assign">Vrijwilligers: woensdag koppelen</div>':''}${x.sunday?`<div class="sunday">${x.sunday}</div>`:''}</div>`)});
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab).classList.add('active')}));
